### ISSUE TITLE
KeyError: 'filters' error

### ISSUE THREAD

**Issue by taoyds** [conala-corpus/conala-baseline#2]
Hi, 

I was trying to run the baseline. While I got the following error: 

`...
unigram_model_trainer.cc(511) LOG(INFO) EM sub_iter=0 size=3548 obj=10.1887 num_tokens=17404 num_tokens/piece=4.9053
unigram_model_trainer.cc(511) LOG(INFO) EM sub_iter=1 size=3138 obj=8.39466 num_tokens=17587 num_tokens/piece=5.60453
trainer_interface.cc(349) LOG(INFO) Saving model: conala-corpus/conala-trainnodev.tspm4000.spm.model
trainer_interface.cc(360) LOG(INFO) Saving vocabs: conala-corpus/conala-trainnodev.tspm4000.spm.vocab
Traceback (most recent call last):
  File "/anaconda3/envs/dy36/bin/xnmt", line 11, in <module>
    load_entry_point('xnmt==0.0.1', 'console_scripts', 'xnmt')()
  File "/anaconda3/envs/dy36/lib/python3.6/site-packages/xnmt-0.0.1-py3.6.egg/xnmt/xnmt_run_experiments.py", line 98, in main
    experiment = initialize_if_needed(uninitialized_exp_args)
  File "/anaconda3/envs/dy36/lib/python3.6/site-packages/xnmt-0.0.1-py3.6.egg/xnmt/persistence.py", line 1297, in initialize_if_needed
    return _YamlDeserializer().initialize_if_needed(root)
  File "/anaconda3/envs/dy36/lib/python3.6/site-packages/xnmt-0.0.1-py3.6.egg/xnmt/persistence.py", line 1038, in initialize_if_needed
    else: return self.initialize_object(deserialized_yaml_wrapper=obj)
  File "/anaconda3/envs/dy36/lib/python3.6/site-packages/xnmt-0.0.1-py3.6.egg/xnmt/persistence.py", line 1081, in initialize_object
    initialized = self.init_components_bottom_up(self.deserialized_yaml)
  File "/anaconda3/envs/dy36/lib/python3.6/site-packages/xnmt-0.0.1-py3.6.egg/xnmt/persistence.py", line 1180, in init_components_bottom_up
    initialized_component = self.init_component(path)
  File "/anaconda3/envs/dy36/lib/python3.6/site-packages/xnmt-0.0.1-py3.6.egg/xnmt/persistence.py", line 1215, in init_component
    initialized_obj = obj.__class__(**init_params)
  File "/anaconda3/envs/dy36/lib/python3.6/site-packages/xnmt-0.0.1-py3.6.egg/xnmt/persistence.py", line 84, in wrapper
    f(obj, **serialize_params)
  File "/anaconda3/envs/dy36/lib/python3.6/site-packages/xnmt-0.0.1-py3.6.egg/xnmt/preproc_runner.py", line 38, in __init__
    task.run_preproc_task(overwrite = overwrite)
  File "/anaconda3/envs/dy36/lib/python3.6/site-packages/xnmt-0.0.1-py3.6.egg/xnmt/preproc_runner.py", line 139, in run_preproc_task
    for my_opts in self.specs}
  File "/anaconda3/envs/dy36/lib/python3.6/site-packages/xnmt-0.0.1-py3.6.egg/xnmt/preproc_runner.py", line 139, in <dictcomp>
    for my_opts in self.specs}
KeyError: 'filters'`

I tried to print `my_opts` in the `preproc_runner.py`,  it looks like:

`{'filenum': 'all', 'spec': [{'type': 'freq', 'min_freq': 2}]}`

Is this error related to the DyNet package installation? Thanks!

**Comment by neubig** [comment]
Hmm, could you try to check out the recommended version of xnmt and see if this fixes the problem?

    cd /path/to/xnmt
    git checkout d9e227b

**Comment by taoyds** [comment]
It fixes the problem by the recommended xnmt version! Thanks!

Btw, are the results of running the baselines supposed to be the same as the numbers on the leaderboard?

**Comment by neubig** [comment]
Great! The scores of the baseline *according to the official scoring script* should be approximately the same as those on the leaderboard, +- a little bit due to random initialization or differences in CUDA libraries, etc.

You can find these in the log file produced by the baseline by doing

    grep "^bleu:" *.log
