### ISSUE TITLE
Problem running Dynet with python3.6

### ISSUE THREAD

**Issue by kev1nramos** [conala-corpus/conala-baseline#3]
This is the output when I run the baseline script.

Anyone can help?

```
Traceback (most recent call last):
  File "/usr/local/bin/xnmt", line 11, in <module>
    load_entry_point('xnmt', 'console_scripts', 'xnmt')()
  File "/home/karsa/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/karsa/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2714, in load_entry_point
    return ep.load()
  File "/home/karsa/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2332, in load
    return self.resolve()
  File "/home/karsa/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/karsa/Desktop/DEV/xnmt/xnmt/__init__.py", line 23, in <module>
    import xnmt.attender
  File "/home/karsa/Desktop/DEV/xnmt/xnmt/attender.py", line 2, in <module>
    import dynet as dy
  File "/home/karsa/.local/lib/python3.6/site-packages/dynet.py", line 25, in <module>
    raise RuntimeError(ERRMSG)
RuntimeError: DyNet was not installed with GPU support. Please see the installation instructions for how to make it possible to use GPUs.
```

**Comment by neerajsharma9195** [comment]
@kev1nramos Were you able to solve this issue?
