### ISSUE TITLE
Memory allocation problem

### ISSUE THREAD

**Issue by glad4enkonm** [conala-corpus/conala-baseline#4]
Hello,

could you please help me. 
Trying to run the baseline, using  xnmt (commit d9e227b).

With GPU (xnmt --dynet-gpu $SDIR/config/$setting.yaml):

```
CUDA failure in cudaMalloc(&ptr, n) 
out of memory

Memory pool info for each devices: 
Device GPU:0 - FOR Memory 560MB, BACK Memory 528MB, PARAM Memory 240MB, SCRATCH Memory 128MB. 
Device CPU - FOR Memory 32MB, BACK Memory 32MB, PARAM Memory 32MB, SCRATCH Memory 32MB. 
CUDA is unable to allocate enough GPU memory on GPU:0, at current stage only 6 MB out of 2004 MB is free. Note due t
o hardware limitations not all free memories can be allocated. 
Traceback (most recent call last): 
 File "/home/noname/repos/CoNaLa/conala/bin/xnmt", line 11, in <module> 
   load_entry_point('xnmt==0.0.1', 'console_scripts', 'xnmt')() 
 File "/home/noname/repos/CoNaLa/conala/lib/python3.6/site-packages/xnmt-0.0.1-py3.6.egg/xnmt/xnmt_run_experiments.
py", line 104, in main 
   eval_scores = experiment(save_fct = lambda: save_to_file(model_file, experiment)) 
 File "/home/noname/repos/CoNaLa/conala/lib/python3.6/site-packages/xnmt-0.0.1-py3.6.egg/xnmt/experiment.py", line 
55, in __call__ 
   self.train.run_training(save_fct = save_fct) 
 File "/home/noname/repos/CoNaLa/conala/lib/python3.6/site-packages/xnmt-0.0.1-py3.6.egg/xnmt/training_regimen.py",
line 137, in run_training 
   self.backward(loss, self.dynet_profiling) 
 File "/home/noname/repos/CoNaLa/conala/lib/python3.6/site-packages/xnmt-0.0.1-py3.6.egg/xnmt/training_regimen.py",
line 40, in backward 
   loss.backward() 
 File "_dynet.pyx", line 823, in _dynet.Expression.backward 
 File "_dynet.pyx", line 842, in _dynet.Expression.backward 
RuntimeError: cudaMalloc(&ptr, n)
```
With CPU (xnmt $SDIR/config/$setting.yaml):
bash conala_baseline.sh    
```
[dynet] random seed: 3672268904 
[dynet] allocating memory: 512MB 
[dynet] memory allocation done. 
running XNMT revision d9e227b on x on 2018-11-18 11:31:52 
=> Running annotmined 
> Preprocessing 
> use randomly initialized DyNet weights of all components 
 DyNet param count: 13692613 
> Training 
The dy.parameter(...) call is now DEPRECATED. 
       There is no longer need to explicitly add parameters to the computation graph. 
       Any used parameter will be added automatically. 
[annotmined] Epoch 0.0104: train_loss/word=7.910845 (words=19235, words/sec=209.41, time=0-00:01:58)
...
[annotmined] Epoch 0.3544: train_loss/word=4.660863 (words=658799, words/sec=250.60, time=0-01:00:05)
Memory pool info for each devices: 
Device CPU - FOR Memory 4080MB, BACK Memory 4080MB, PARAM Memory 240MB, SCRATCH Memory 128MB. 
CPU memory allocation failed n=4278190080 align=32 
Traceback (most recent call last): 
 File "/home/noname/repos/CoNaLa/conala/bin/xnmt", line 11, in <module> 
   load_entry_point('xnmt==0.0.1', 'console_scripts', 'xnmt')() 
 File "/home/noname/repos/CoNaLa/conala/lib/python3.6/site-packages/xnmt-0.0.1-py3.6.egg/xnmt/xnmt_run_experiments.
py", line 104, in main 
   eval_scores = experiment(save_fct = lambda: save_to_file(model_file, experiment)) 
 File "/home/noname/repos/CoNaLa/conala/lib/python3.6/site-packages/xnmt-0.0.1-py3.6.egg/xnmt/experiment.py", line 
55, in __call__ 
   self.train.run_training(save_fct = save_fct) 
 File "/home/noname/repos/CoNaLa/conala/lib/python3.6/site-packages/xnmt-0.0.1-py3.6.egg/xnmt/training_regimen.py",
line 137, in run_training 
   self.backward(loss, self.dynet_profiling) 
 File "/home/noname/repos/CoNaLa/conala/lib/python3.6/site-packages/xnmt-0.0.1-py3.6.egg/xnmt/training_regimen.py",
line 40, in backward 
   loss.backward() 
 File "_dynet.pyx", line 823, in _dynet.Expression.backward 
 File "_dynet.pyx", line 842, in _dynet.Expression.backward 
RuntimeError: CPU memory allocation failed`
```

**Comment by pcyin** [comment]
@neubig is this because of insufficient GPU memory?

**Comment by neubig** [comment]
Yes, probably. It looks like your GPU has 8gb, but the baseline was run on a GPU with 11gb.

**Comment by glad4enkonm** [comment]
@neubig is it possible to run the baseline without GPU? 
By changing 
`xnmt --dynet-gpu $SDIR/config/$setting.yaml`
to
`xnmt $SDIR/config/$setting.yaml`
in conala_baseline.sh

**Comment by dsmic** [comment]
Can you give an idea of the running time in case of CPU? Or is there a way to reduce GPU memory usage?
